spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javatechie?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  # No external messaging configured in this simplified setup


order:
  event:
    topicName: order-events